# Setup
title:        ChenData
tagline:      Project Page for Data Analysis
url:          "http://chen-node.com/ChenData"
baseurl:      "/ChenData"
paginate:     1

# About/contact
author:
  name:       Chen Xie
  url:        http://github.com/neilChenXie

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
