# Setup
title:        ChenData
tagline:      A responsive theme for your project on GitHub Pages
url:          "http://chen-node.com/ChenNote"
baseurl:      "/ChenData"
paginate:     1

# About/contact
author:
  name:       Chen Xie
  url:        http://chen-node.com/about

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
